### ISSUE TITLE
[Question] Same process for init_boot.img?

### ISSUE THREAD

**Issue by DineshValor** [gitclone-url/Boot-img-flasher#1]
I'm wondering the process is same for init_boot.img flash?

**Comment by DineshValor** [comment]
Fix "STOCK BOOT.IMG NOT NOT FOUND" by magisk canary using Termux

-> Download stock boot.img (init_boot.img mostly in android 14 out of the box)

-> For boot.img
>
ls -d /dev/block/*/*/*/by-name/boot*
>
ls -d /storage/*/*/*/boot.img
>

<Modify 3rd command line according to first 2 commands output>

dd if=/storage/emulated/0/Download/boot.img of=/dev/block/platform/soc/112b0000.ufshci/by-name/boot_b
-> For init_boot.img
>
ls -d /dev/block/*/*/*/by-name/init_boot*
>
ls -d /storage/*/*/*/init_boot.img
>

<Modify 3rd command line according to first 2 commands output>

dd if=/storage/emulated/0/Download/init_boot.img of=/dev/block/platform/soc/112b0000.ufshci/by-name/init_boot_b

**Comment by gitclone-url** [comment]
> I'm wondering the process is same for init_boot.img flash?

The partition for init_boot is different, so the script currently doesn't find init_boot partition only the boot(s) partitions. But if you want you can modify the script to search for init_boot in find_boot_block function call at https://github.com/gitclone-url/Boot-img-flasher/blob/8642dcf097ff022f525deb4ca715a3ebf4ddfa88/boot-img-flasher.sh#L196... 

I will try implement it in next week thanks for your concern 😀

**Comment by gitclone-url** [comment]
@DineshValor and I didn't understood your 1st comment. please can you be more specific? https://github.com/gitclone-url/Boot-img-flasher/issues/1#issuecomment-2259851120
