### ISSUE TITLE
I cannot install it to the termux. 

### ISSUE THREAD

**Issue by Nobody0x00** [gitclone-url/Boot-img-flasher#3]
I tried so many things but the script cannot install to termux. I don't know why. Termux doesn't give any error reports about the installation. I write the command for install it   and nothing happens. Please someone help me.

**Comment by gitclone-url** [comment]
Which command, and what you was expecting that not happening?

**Comment by gitclone-url** [comment]
@ValiantDeveloper I need further information, if you don't reply I will close this issue!

**Comment by Nobody0x00** [comment]
> @ValiantDeveloper I need further information, if you don't reply I will close this issue!

The command is this "_curl -s https://raw.githubusercontent.com/gitclone-url/Boot-img-flasher/master/boot-img-flasher.sh -o boot-img-flasher.sh && { command -v tput >/dev/null && command -v figlet >/dev/null && command -v file >/dev/null || pkg install -y figlet file ncurses-utils; } && { command -v sudo >/dev/null || pkg install -y tsu; }_". When I wrote it nothing happens.
I tried to download the tools without this command. After run it again but it doesn't work. What should I do? And I'm sorry because I'm late to answer you. The notification didn't arrive at me.

**Comment by gitclone-url** [comment]
@ValiantDeveloper  - This one-liner command only downloads the script file and the required tools. To check if the download worked, use the `ls` command in your terminal. If you don't see the script file (boot-img-flasher.sh), you might need to install `curl` first:

```bash
pkg install curl
```

Contact me on Telegram for further help https://t.me/PhantomXPain

**Comment by Nobody0x00** [comment]
@gitclone-url I used the command that is _ls_ and I can see the script in list and curl is the newest version, too. But I can't use the script. When I try to use it termux says _command not found_.

**Comment by gitclone-url** [comment]
@ValiantDeveloper Do you have root access on your phone? If yes did you granted access to termux?

If both answer is yes, then simply run the script with `sudo bash`

**Comment by Nobody0x00** [comment]
@gitclone-url It worked. Thanks a lot. But I have another question. Can I flash a custom recovery img? If the answer is yes then how?  And what's the difference between "_boot_" and "init_boot"?

**Comment by gitclone-url** [comment]
Okay I am happy to know that it worked for you 😃

Please check the [Examples of Use](https://github.com/gitclone-url/Boot-img-flasher?tab=readme-ov-file#examples-of-use) section in the readme for further understanding of script usage. And regarding your question about recovery image - No, this tool is specifically designed to flash only boot.img and init_boot.img files. I have clearly mentioned it in the project description.

This tool can't flash recovery image file , If you want to know how to flash recovery on phone do contact me on Telegram and Google up to know the difference between every partition.
